### ISSUE TITLE
json parse fails when not sending json data over ws

### ISSUE THREAD

**Issue by NoeelMoeskops** [aruna-rov/companion#1]
when sending a string over the websocket ("hallo") the json parser fails.
server output:
```
(node:9925) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/noeel/Documents/git/aruna-companion/src/server.ts:23:24)
    at Generator.next (<anonymous>)
    at /home/noeel/Documents/git/aruna-companion/src/server.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/noeel/Documents/git/aruna-companion/src/server.ts:3:12)
    at WebSocket.ws.on (/home/noeel/Documents/git/aruna-companion/src/server.ts:22:58)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:441:20)
    at Receiver.receiverOnMessage (/home/noeel/Documents/git/aruna-companion/node_modules/ws/lib/websocket.js:789:20)
(node:9925) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)


(node:9925) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9925) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token b in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/noeel/Documents/git/aruna-companion/src/server.ts:23:24)
    at Generator.next (<anonymous>)
    at /home/noeel/Documents/git/aruna-companion/src/server.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/noeel/Documents/git/aruna-companion/src/server.ts:3:12)
    at WebSocket.ws.on (/home/noeel/Documents/git/aruna-companion/src/server.ts:22:58)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:441:20)
    at Receiver.receiverOnMessage (/home/noeel/Documents/git/aruna-companion/node_modules/ws/lib/websocket.js:789:20)
(node:9925) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by NoeelMoeskops** [comment]
I now get how the websocket works. It needs a path or message type.
